# Generated by rust2rpm 18
%bcond_without check
%global __cargo_skip_build 0

%global crate soi

Name:           rust-%{crate}
Version:        0.1.0
Release:        1%{?dist}
Summary:        Command line music player for the pre-streaming era

License:        CC0

URL:            https://crates.io/crates/soi
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Command line music player for the pre-streaming era.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license COPYING
%doc README.md
%{_bindir}/soi

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 03 2021 teervo <teervo@protonmail.com> - 0.1.0-1
- Initial package
